Repository AgileMentor/AgileMentor, pull requests merged in 2024-11, with the labels that each got.

#7 feat: 소개 페이지 구현 및 경로 alias 설정
  frontend/config-overrides.js
  frontend/jsconfig.json
  frontend/jsconfig.paths.json
  frontend/package.json
  frontend/public/image/google_login.png
  frontend/public/image/logo.png
  frontend/src/components/common/IconLabelCard/index.jsx
  frontend/src/components/common/LoginButton/index.jsx
  frontend/src/components/features/Header.jsx
  frontend/src/pages/Introduce/index.jsx
  frontend/src/styles/globalStyle.js
Labels: Feat, FE

#12 [FEAT] 구글 로그인 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/agilementor/AgilementorApplication.java
  backend/src/main/java/agilementor/member/controller/AuthController.java
  backend/src/main/java/agilementor/member/dto/GoogleTokenResponse.java
  backend/src/main/java/agilementor/member/dto/ParsedIdToken.java
  backend/src/main/java/agilementor/member/entity/Member.java
  backend/src/main/java/agilementor/member/properties/GoogleClientProperties.java
  backend/src/main/java/agilementor/member/properties/GoogleProviderProperties.java
  backend/src/main/java/agilementor/member/repository/MemberRepository.java
  backend/src/main/java/agilementor/member/service/AuthClientService.java
  backend/src/main/java/agilementor/member/service/MemberService.java
  backend/src/main/java/agilementor/member/util/JwtParser.java
  backend/src/main/resources/application.properties
  backend/src/test/java/agilementor/member/repository/MemberRepositoryTest.java
  backend/src/test/java/agilementor/member/service/AuthClientServiceTest.java
  backend/src/test/java/agilementor/member/service/MemberServiceTest.java
  backend/src/test/java/agilementor/member/util/JwtParserTest.java
Labels: Feat, BE, Test

#20 [CHORE] 빌드 설정 변경
  backend/build.gradle
Labels: BE, Chore

#22 [FEAT] 예외 처리 로직 구현
  backend/src/main/java/agilementor/common/exception/ExceptionResponse.java
  backend/src/main/java/agilementor/common/exception/ExternalServerErrorException.java
  backend/src/main/java/agilementor/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/agilementor/common/exception/SocialLoginFailException.java
  backend/src/main/java/agilementor/member/service/AuthClientService.java
  backend/src/test/java/agilementor/member/service/AuthClientServiceTest.java
Labels: Feat, BE

#24 [FEAT] 대시보드 페이지 구현
  frontend/public/image/chatgpt_icon.png
  frontend/public/image/github_icon.png
  frontend/public/image/googledrive_icon.png
  frontend/public/image/notion_icon.png
  frontend/public/image/slack_icon.png
  frontend/src/components/common/ExternalLinkButtons/index.jsx
  frontend/src/components/common/OngoingTasksList/index.jsx
  frontend/src/components/common/ProjectList/index.jsx
  frontend/src/components/common/SelectProject/index.jsx
  frontend/src/components/features/SideMenu.jsx
  frontend/src/mocks/mockBacklogs.js
  frontend/src/mocks/mockProjects.js
  frontend/src/pages/Dashboard/index.jsx
Labels: Feat, FE

#29 [Refactor] 공통 사이드 바 구현
  backend/build.gradle
  backend/src/main/java/agilementor/common/exception/ExceptionResponse.java
  backend/src/main/java/agilementor/common/exception/ExternalServerErrorException.java
  backend/src/main/java/agilementor/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/agilementor/common/exception/SocialLoginFailException.java
  backend/src/main/java/agilementor/member/service/AuthClientService.java
  backend/src/test/java/agilementor/member/service/AuthClientServiceTest.java
  frontend/jsconfig.json
  frontend/package.json
  frontend/public/image/chatgpt_icon.png
  frontend/public/image/github_icon.png
  frontend/public/image/googledrive_icon.png
  frontend/public/image/notion_icon.png
  frontend/public/image/slack_icon.png
  frontend/src/App.js
  frontend/src/components/common/ExternalLinkButtons/index.jsx
  frontend/src/components/common/Kanban/index.jsx
  frontend/src/components/common/KanbanCard/index.jsx
  frontend/src/components/common/LogoutButton/index.jsx
  frontend/src/components/common/Member/index.jsx
  frontend/src/components/common/MenuContent/index.jsx
  frontend/src/components/common/NavigateMenu/index.jsx
  frontend/src/components/common/NewProject/index.jsx
  frontend/src/components/common/OngoingTasksList/index.jsx
  frontend/src/components/common/ProjectList/index.jsx
  frontend/src/components/common/SelectProject/index.jsx
  frontend/src/components/features/Header.jsx
  frontend/src/components/features/SideBar.jsx
  frontend/src/components/features/SideMenu.jsx
  frontend/src/mocks/mockBacklogs.js
  frontend/src/mocks/mockProjects.js
  frontend/src/pages/Dashboard/index.jsx
  frontend/src/pages/Kanbanboard/index.jsx
  frontend/src/styles/globalStyle.js
Labels: Refactor, FE

#34 [REFACTOR] 공통 사이드 바 수정, [FEAT] 모달(프로젝트 생성, 멤버 초대) 구현
  frontend/src/components/common/Member/index.jsx
  frontend/src/components/common/MinModal/index.jsx
  frontend/src/components/common/NavigateMenu/index.jsx
  frontend/src/components/common/NewProject/index.jsx
  frontend/src/components/common/SelectProject/index.jsx
  frontend/src/components/features/SideBar.jsx
Labels: Feat, Refactor, FE

#38 [Refactor] 공통 사이드바 및 페이지 레이아웃 수정
  frontend/src/components/common/Member/index.jsx
  frontend/src/components/common/NavigateMenu/index.jsx
  frontend/src/components/common/NewProject/index.jsx
  frontend/src/components/common/SelectProject/index.jsx
  frontend/src/components/features/SideBar.jsx
  frontend/src/pages/Burndown/index.jsx
  frontend/src/pages/Dashboard/index.jsx
  frontend/src/pages/Kanbanboard/index.jsx
Labels: Refactor, FE

#42 [Docs] README.md 파일 업데이트
  README.md
Labels: Docs

#44 [FEAT] 백로그 페이지 모달 구현
  frontend/package.json
  frontend/src/components/common/AIModal/index.jsx
  frontend/src/components/common/BacklogModal/index.jsx
  frontend/src/components/common/SprintStartModal/index.jsx
Labels: Feat, FE

#41 [FEAT] 프로젝트 CRUD 구현
  backend/src/main/java/agilementor/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/agilementor/common/exception/MemberNotFoundException.java
  backend/src/main/java/agilementor/common/exception/ProjectNotFoundException.java
  backend/src/main/java/agilementor/common/exception/SocialLoginFailException.java
  backend/src/main/java/agilementor/member/dto/response/MemberGetResponse.java
  backend/src/main/java/agilementor/project/controller/ProjectController.java
  backend/src/main/java/agilementor/project/dto/request/ProjectCreateRequest.java
  backend/src/main/java/agilementor/project/dto/request/ProjectUpdateRequest.java
  backend/src/main/java/agilementor/project/dto/response/ProjectResponse.java
  backend/src/main/java/agilementor/project/entity/Project.java
  backend/src/main/java/agilementor/project/entity/ProjectMember.java
  backend/src/main/java/agilementor/project/repository/ProjectMemberRepository.java
  backend/src/main/java/agilementor/project/repository/ProjectRespository.java
  backend/src/main/java/agilementor/project/service/ProjectService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/agilementor/project/service/ProjectServiceTest.java
Labels: Feat, BE

#49 Feat/48 로그인 api연결
  frontend/src/components/common/LoginButton/index.jsx
  frontend/src/pages/Introduce/index.jsx
Labels: Feat, FE

#51 [FEAT] 프로젝트 라우터 설정
  frontend/config-overrides.js
  frontend/jsconfig.json
  frontend/jsconfig.paths.json
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/Layout/index.jsx
  frontend/src/components/common/LogoutButton/index.jsx
  frontend/src/index.css
  frontend/src/pages/Burndown/index.jsx
  frontend/src/pages/Dashboard/index.jsx
  frontend/src/pages/Kanbanboard/index.jsx
  frontend/src/routes/index.jsx
  frontend/src/routes/path.js
Labels: Feat, FE

#53 [FEAT] 프로젝트 생성, 조회 API 연결
  frontend/src/App.js
  frontend/src/components/common/MinModal/index.jsx
  frontend/src/components/common/NewProject/index.jsx
  frontend/src/components/common/ProjectList/index.jsx
  frontend/src/components/common/SelectProject/index.jsx
  frontend/src/components/features/SideBar.jsx
  frontend/src/provider/projectContext.js
Labels: Feat, FE

#56 [FEAT] 프로젝트 회원 관리 기능 및 초대 관련 구현
  backend/src/main/java/agilementor/common/exception/AlreadyJoinedMemberException.java
  backend/src/main/java/agilementor/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/agilementor/common/exception/InvalidInvitationException.java
  backend/src/main/java/agilementor/common/exception/KickOneselfException.java
  backend/src/main/java/agilementor/common/exception/MemberNotFoundException.java
  backend/src/main/java/agilementor/common/exception/NotProjectAdminException.java
  backend/src/main/java/agilementor/project/controller/InvitationController.java
  backend/src/main/java/agilementor/project/controller/ProjectController.java
  backend/src/main/java/agilementor/project/controller/ProjectMemberController.java
  backend/src/main/java/agilementor/project/dto/request/ProjectInviteRequest.java
  backend/src/main/java/agilementor/project/dto/response/InvitationGetResponse.java
  backend/src/main/java/agilementor/project/dto/response/ProejctMemberResponse.java
  backend/src/main/java/agilementor/project/entity/Invitation.java
  backend/src/main/java/agilementor/project/entity/ProjectMember.java
  backend/src/main/java/agilementor/project/repository/InvitationRepository.java
  backend/src/main/java/agilementor/project/service/InvitationService.java
  backend/src/main/java/agilementor/project/service/ProjectMemberService.java
  backend/src/main/java/agilementor/project/service/ProjectService.java
  backend/src/test/java/agilementor/project/service/InvitationServiceTest.java
  backend/src/test/java/agilementor/project/service/ProjectMemberServiceTest.java
  backend/src/test/java/agilementor/project/service/ProjectServiceTest.java
Labels: Feat, BE

#58 [FEAT] 회원 본인 정보 조회 기능 구현
  backend/src/main/java/agilementor/member/controller/MemberController.java
  backend/src/main/java/agilementor/member/dto/response/MemberGetResponse.java
  backend/src/main/java/agilementor/member/service/MemberService.java
  backend/src/test/java/agilementor/member/service/MemberServiceTest.java
Labels: Feat, BE

#62 [FEAT] 스프린트 수정
  backend/src/main/java/agilementor/common/exception/EndDateNullException.java
  backend/src/main/java/agilementor/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/agilementor/common/exception/SprintNotFoundException.java
  backend/src/main/java/agilementor/common/exception/TitleNullException.java
  backend/src/main/java/agilementor/sprint/controller/SprintController.java
  backend/src/main/java/agilementor/sprint/entity/Sprint.java
  backend/src/main/java/agilementor/sprint/repository/SprintRepository.java
  backend/src/main/java/agilementor/sprint/service/SprintService.java
  backend/src/test/java/agilementor/sprint/service/SprintServiceTest.java
Labels: Feat, BE

#63 [FEAT] 백로그 및 스프린트 페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/common/Backlog/index.jsx
  frontend/src/components/common/BacklogBar/index.jsx
  frontend/src/components/common/SelectProject/index.jsx
  frontend/src/components/common/Sprint/index.jsx
  frontend/src/components/common/SprintBar/index.jsx
  frontend/src/components/common/Story/index.jsx
  frontend/src/components/features/SideBar.jsx
  frontend/src/pages/BacklogAndSprint/index.jsx
  frontend/src/provider/projectContext.js
Labels: Feat, FE
