Repository AgileMentor/AgileMentor, pull requests merged in 2024-12, with the labels that each got.

#68 [FIX] 세션 유효성 검증 기능 추가, 초대 기능 수정
  backend/src/main/java/agilementor/common/config/WebConfig.java
  backend/src/main/java/agilementor/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/agilementor/common/exception/InvalidSessionException.java
  backend/src/main/java/agilementor/common/filter/SessionValidationFilter.java
  backend/src/main/java/agilementor/project/controller/ProjectMemberController.java
Labels: BE, Fix

#70 [FEAT] 멤버 목록 조회, 초대, 추방 API 연결
  frontend/src/components/common/Member/index.jsx
  frontend/src/components/features/SideBar.jsx
  frontend/src/provider/projectContext.js
Labels: Feat, FE

#71 [FEAT] 백로그, 스토리 관련 API 구현
  backend/src/main/java/agilementor/backlog/controller/BacklogController.java
  backend/src/main/java/agilementor/backlog/controller/StoryController.java
  backend/src/main/java/agilementor/backlog/controller/TaskController.java
  backend/src/main/java/agilementor/backlog/dto/request/BacklogCreateRequest.java
  backend/src/main/java/agilementor/backlog/dto/request/BacklogUpdateRequest.java
  backend/src/main/java/agilementor/backlog/dto/request/StoryCreateRequest.java
  backend/src/main/java/agilementor/backlog/dto/request/StoryUpdateRequest.java
  backend/src/main/java/agilementor/backlog/dto/response/BacklogCreateResponse.java
  backend/src/main/java/agilementor/backlog/dto/response/BacklogGetResponse.java
  backend/src/main/java/agilementor/backlog/dto/response/BacklogUpdateResponse.java
  backend/src/main/java/agilementor/backlog/dto/response/StoryCreateResponse.java
  backend/src/main/java/agilementor/backlog/dto/response/StoryGetResponse.java
  backend/src/main/java/agilementor/backlog/dto/response/StoryUpdateResponse.java
  backend/src/main/java/agilementor/backlog/entity/Backlog.java
  backend/src/main/java/agilementor/backlog/entity/Priority.java
  backend/src/main/java/agilementor/backlog/entity/Status.java
  backend/src/main/java/agilementor/backlog/entity/Story.java
  backend/src/main/java/agilementor/backlog/repository/BacklogRepository.java
  backend/src/main/java/agilementor/backlog/repository/StoryRepository.java
  backend/src/main/java/agilementor/backlog/service/BacklogService.java
  backend/src/main/java/agilementor/backlog/service/StoryService.java
  backend/src/main/java/agilementor/common/exception/BacklogNotFoundException.java
  backend/src/main/java/agilementor/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/agilementor/common/exception/StoryNotFoundException.java
  backend/src/main/java/agilementor/sprint/repository/SprintRepository.java
Labels: Feat, BE

#72 [FEAT] 프로젝트 삭제, 수정, 나가기, 초대 관리 API 연동
  frontend/src/App.js
  frontend/src/components/common/CreateProjectButton/index.jsx
  frontend/src/components/common/DeleteConfirmModal/index.jsx
  frontend/src/components/common/LoginButton/index.jsx
  frontend/src/components/common/LogoutButton/index.jsx
  frontend/src/components/common/Member/index.jsx
  frontend/src/components/common/ProjectList/index.jsx
  frontend/src/components/common/ProjectSettingModal/index.jsx
  frontend/src/components/common/SettingButton/index.jsx
  frontend/src/components/features/Header.jsx
  frontend/src/components/features/SideBar.jsx
  frontend/src/pages/Dashboard/index.jsx
  frontend/src/provider/projectContext.js
Labels: Feat, FE

#75 [FEAT] 테스트 서버 배포 관련 설정 및 백엔드 배포 자동화 적용
  .github/workflows/Backend_CD.yml
  backend/.gitignore
  backend/src/main/java/agilementor/backlog/entity/Backlog.java
  backend/src/main/java/agilementor/common/config/SwaggerConfig.java
  backend/src/main/java/agilementor/common/config/WebConfig.java
  backend/src/main/java/agilementor/member/controller/AuthController.java
  backend/src/main/resources/application.properties
Labels: Feat, BE

#79 [FIX] 백엔드 배포 자동화 오류 수정
  .github/workflows/Backend_CD.yml
Labels: BE, Fix

#80 [FEAT] ai 기능 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/agilementor/backlog/repository/BacklogRepository.java
  backend/src/main/java/agilementor/chatgpt/controller/GPTController.java
  backend/src/main/java/agilementor/chatgpt/dto/BacklogResponseDTO.java
  backend/src/main/java/agilementor/chatgpt/dto/GPTRequest.java
  backend/src/main/java/agilementor/chatgpt/dto/GPTResponse.java
  backend/src/main/java/agilementor/chatgpt/dto/ProjectResponseDTO.java
  backend/src/main/java/agilementor/chatgpt/dto/SprintResponseDTO.java
  backend/src/main/java/agilementor/chatgpt/dto/StoryResponseDTO.java
  backend/src/main/java/agilementor/chatgpt/service/GPTService.java
  backend/src/main/java/agilementor/common/exception/AlreadyJoinedMemberException.java
  backend/src/main/java/agilementor/common/exception/FailedToParseException.java
  backend/src/main/java/agilementor/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/agilementor/common/exception/NotJsonResponseException.java
  backend/src/main/java/agilementor/project/controller/ProjectMemberController.java
  backend/src/main/java/agilementor/sprint/controller/SprintController.java
  backend/src/main/java/agilementor/sprint/dto/CompletedSprintData.java
  backend/src/main/java/agilementor/sprint/entity/Sprint.java
  backend/src/main/java/agilementor/sprint/repository/SprintRepository.java
  backend/src/main/java/agilementor/sprint/service/SprintService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/agilementor/sprint/service/SprintServiceTest.java
Labels: Feat, BE

#84 [FEAT] 스토리 관리 기능 추가 및 ProjectContext 기반 백로그/스프린트 리팩토링
  frontend/src/components/common/Backlog/index.jsx
  frontend/src/components/common/BacklogBar/index.jsx
  frontend/src/components/common/BacklogModal/index.jsx
  frontend/src/components/common/NewBacklogModal/index.jsx
  frontend/src/components/common/NewStoryModal/index.jsx
  frontend/src/components/common/Sprint/index.jsx
  frontend/src/components/common/SprintSettingModal/index.jsx
  frontend/src/components/common/SprintStartModal/index.jsx
  frontend/src/components/common/Story/index.jsx
  frontend/src/components/common/StoryDetailsModal/index.jsx
  frontend/src/pages/BacklogAndSprint/index.jsx
  frontend/src/provider/projectContext.js
Labels: Feat, FE

#87 [FIX] 프로젝트 삭제, 탈퇴, 추방시 스프린트,스토리,백로그 처리 로직 추가
  backend/src/main/java/agilementor/backlog/entity/Backlog.java
  backend/src/main/java/agilementor/backlog/repository/BacklogRepository.java
  backend/src/main/java/agilementor/backlog/repository/StoryRepository.java
  backend/src/main/java/agilementor/project/service/ProjectMemberService.java
  backend/src/main/java/agilementor/project/service/ProjectService.java
  backend/src/main/java/agilementor/sprint/repository/SprintRepository.java
  backend/src/test/java/agilementor/project/service/ProjectMemberServiceTest.java
  backend/src/test/java/agilementor/project/service/ProjectServiceTest.java
Labels: BE, Fix

#89 [FEAT] 번다운 차트, 칸반 보드, AI 기능 API 연결
  frontend/src/components/common/AIModal/index.jsx
  frontend/src/components/common/BurndownChart/index.jsx
  frontend/src/components/common/Kanban/index.jsx
  frontend/src/components/common/KanbanCard/index.jsx
  frontend/src/pages/BacklogAndSprint/index.jsx
  frontend/src/pages/Burndown/index.jsx
  frontend/src/pages/Kanbanboard/index.jsx
  frontend/src/provider/projectContext.js
Labels: Feat, FE

#91 [FEAT] 애자일 학습하기 페이지 구현 및 대시보드 페이지 기능 추가
  frontend/public/image/backlog.png
  frontend/public/image/ci.png
  frontend/public/image/continuousimprovement.png
  frontend/public/image/dailyscrum.png
  frontend/public/image/enhancecommunication.png
  frontend/public/image/featurefocus.png
  frontend/public/image/feedbackimprovement.png
  frontend/public/image/flowmanagement.png
  frontend/public/image/iterativedevelopment.png
  frontend/public/image/kanbanboard.png
  frontend/public/image/learningamplification.png
  frontend/public/image/moscowpriority.png
  frontend/public/image/pairprogramming.png
  frontend/public/image/rapiddelivery.png
  frontend/public/image/refactoring.png
  frontend/public/image/regularrelease.png
  frontend/public/image/removewaste.png
  frontend/public/image/retrospective.png
  frontend/public/image/roledivision.png
  frontend/public/image/smallrelease.png
  frontend/public/image/sprint.png
  frontend/public/image/sprintplanning.png
  frontend/public/image/sprintreview.png
  frontend/public/image/tailoredapproach.png
  frontend/public/image/tdd.png
  frontend/public/image/timeboxing.png
  frontend/public/image/userparticipation.png
  frontend/public/image/visualizeWork.png
  frontend/public/image/wiplimit.png
  frontend/src/components/Layout/index.jsx
  frontend/src/components/common/AgileNotesList/index.jsx
  frontend/src/components/common/AgileSideBar/index.jsx
  frontend/src/components/common/NavigateMenu/index.jsx
  frontend/src/components/common/OngoingTasksList/index.jsx
  frontend/src/contentData.js
  frontend/src/pages/AgileStudy/index.jsx
  frontend/src/routes/index.jsx
  frontend/src/routes/path.js
Labels: Feat, FE

#93 [FEAT] AgileMentor 서비스 도움말 기능 추가
  frontend/public/image/addProject.png
  frontend/public/image/agileSideBar.png
  frontend/public/image/agilestudy.png
  frontend/public/image/bell.png
  frontend/public/image/burndown.png
  frontend/public/image/inviteMember.png
  frontend/public/image/kanbanhelp.png
  frontend/public/image/member.png
  frontend/public/image/myProject.png
  frontend/public/image/navigateMenu.png
  frontend/public/image/newProject.png
  frontend/public/image/onTasking.png
  frontend/public/image/selectProject.png
  frontend/public/image/setting.png
  frontend/public/image/settingDelete.png
  frontend/public/image/siteMenu.png
  frontend/public/image/studyAgile.png
  frontend/src/components/Layout/index.jsx
  frontend/src/components/common/CommonHelpButton/index.jsx
  frontend/src/components/common/CommonHelpModal/index.jsx
  frontend/src/components/common/HelpAgileStudyModal/index.jsx
  frontend/src/components/common/HelpBurndownModal/index.jsx
  frontend/src/components/common/HelpComponent/index.jsx
  frontend/src/components/common/HelpDashboardModal/index.jsx
  frontend/src/components/common/HelpKanbanboardModal/index.jsx
  frontend/src/pages/AgileStudy/index.jsx
  frontend/src/pages/BacklogAndSprint/index.jsx
  frontend/src/pages/Burndown/index.jsx
  frontend/src/pages/Dashboard/index.jsx
  frontend/src/pages/Kanbanboard/index.jsx
Labels: Feat, FE

#98 [FEAT] 백로그 상태 및 스프린트 관리 개선, 불필요한 코드 정리 및 OngoingTasksList API 연동 추가
  frontend/src/components/common/Backlog/index.jsx
  frontend/src/components/common/BacklogBar/index.jsx
  frontend/src/components/common/BacklogModal/index.jsx
  frontend/src/components/common/CommonHelpButton/index.jsx
  frontend/src/components/common/CommonHelpModal/index.jsx
  frontend/src/components/common/OngoingTasksList/index.jsx
  frontend/src/components/common/Sprint/index.jsx
  frontend/src/components/common/SprintBar/index.jsx
  frontend/src/mocks/mockBacklogs.js
  frontend/src/mocks/mockProjects.js
  frontend/src/mocks/mockSprints.js
  frontend/src/pages/BacklogAndSprint/index.jsx
  frontend/src/pages/Dashboard/index.jsx
  frontend/src/provider/projectContext.js
Labels: Feat, FE, Fix

#99 [FEAT] AgileMentor 서비스 배포
  frontend/src/components/common/LoginButton/index.jsx
Labels: Feat, FE

#95 [FIX] ai 프롬프트 수정
  backend/src/main/java/agilementor/chatgpt/service/GPTService.java
Labels: BE, Fix

#101 [FIX] 프론트 URL 수정
  backend/src/main/java/agilementor/member/controller/AuthController.java
Labels: BE, Fix

#102 [FIX] 서비스 배포 코드 수정
  frontend/.eslintrc.json
  frontend/babel.config.js
  frontend/config-overrides.js
  frontend/package-lock.json
  frontend/package.json
Labels: Feat, FE

#104 [TEST, FIX] 스토리, 백로그 기능 테스트 코드 작성 및 백로그 기능 오류 수정
  backend/src/main/java/agilementor/backlog/dto/request/BacklogCreateRequest.java
  backend/src/main/java/agilementor/backlog/dto/request/BacklogUpdateRequest.java
  backend/src/main/java/agilementor/backlog/dto/request/StoryUpdateRequest.java
  backend/src/main/java/agilementor/backlog/entity/Backlog.java
  backend/src/main/java/agilementor/backlog/entity/Priority.java
  backend/src/main/java/agilementor/backlog/entity/Status.java
  backend/src/main/java/agilementor/backlog/service/BacklogService.java
  backend/src/main/java/agilementor/sprint/repository/SprintRepository.java
  backend/src/test/java/agilementor/backlog/service/BacklogServiceTest.java
  backend/src/test/java/agilementor/backlog/service/StoryServiceTest.java
  backend/src/test/java/agilementor/project/service/ProjectMemberServiceTest.java
  backend/src/test/java/agilementor/project/service/ProjectServiceTest.java
Labels: Refactor, BE, Test, Fix

#111 [FEAT, FIX] swagger api 설명 작성, 백로그와 스토리 생성 성공 응답 상태코드 수정
  backend/src/main/java/agilementor/backlog/controller/BacklogController.java
  backend/src/main/java/agilementor/backlog/controller/StoryController.java
  backend/src/main/java/agilementor/backlog/controller/TaskController.java
  backend/src/main/java/agilementor/chatgpt/controller/GPTController.java
  backend/src/main/java/agilementor/common/config/SwaggerConfig.java
  backend/src/main/java/agilementor/member/controller/MemberController.java
  backend/src/main/java/agilementor/project/controller/InvitationController.java
  backend/src/main/java/agilementor/project/controller/ProjectController.java
  backend/src/main/java/agilementor/project/controller/ProjectMemberController.java
  backend/src/main/java/agilementor/sprint/controller/SprintController.java
Labels: Feat, BE, Fix

#113 [FIX] 세션 검증 기능 재구현
  backend/src/main/java/agilementor/backlog/controller/BacklogController.java
  backend/src/main/java/agilementor/backlog/controller/StoryController.java
  backend/src/main/java/agilementor/backlog/controller/TaskController.java
  backend/src/main/java/agilementor/chatgpt/controller/GPTController.java
  backend/src/main/java/agilementor/common/annotation/LoginMemberId.java
  backend/src/main/java/agilementor/common/config/WebConfig.java
  backend/src/main/java/agilementor/common/filter/SessionValidationFilter.java
  backend/src/main/java/agilementor/common/resolver/LoginMemberIdArgumentResolver.java
  backend/src/main/java/agilementor/member/controller/MemberController.java
  backend/src/main/java/agilementor/project/controller/InvitationController.java
  backend/src/main/java/agilementor/project/controller/ProjectController.java
  backend/src/main/java/agilementor/project/controller/ProjectMemberController.java
  backend/src/main/java/agilementor/sprint/controller/SprintController.java
Labels: BE, Fix

#115 [FIX] 세션 유효기간, cors 설정 변경
  backend/src/main/java/agilementor/common/config/WebConfig.java
  backend/src/main/resources/application.properties
Labels: BE, Fix

#117 [FIX] swagger cors 오류 해결
  backend/src/main/java/agilementor/common/config/WebConfig.java
Labels: BE, Fix

#109 [FIX] 토큰수 증가
  backend/src/main/java/agilementor/chatgpt/service/GPTService.java
Labels: BE, Fix

#118 [DOCS] README 업데이트
  README.md
Labels: Docs

#105 [FIX] UI/UX 수정 및 개선 작업
  frontend/src/components/Layout/index.jsx
  frontend/src/components/common/BacklogModal/index.jsx
  frontend/src/components/common/CommonHelpButton/index.jsx
  frontend/src/components/common/LogoutButton/index.jsx
  frontend/src/components/common/NavigateMenu/index.jsx
  frontend/src/components/common/NewBacklogModal/index.jsx
  frontend/src/components/common/ProjectList/index.jsx
  frontend/src/components/common/ProjectSettingModal/index.jsx
  frontend/src/components/features/Header.jsx
  frontend/src/components/features/SideBar.jsx
  frontend/src/pages/Burndown/index.jsx
  frontend/src/pages/Dashboard/index.jsx
  frontend/src/pages/Kanbanboard/index.jsx
Labels: FE, Fix

#110 [FEAT] 서비스 제목 추가 및 UI 개선
  frontend/public/favicon.ico
  frontend/public/image/SprintContainer.png
  frontend/public/image/backlogContainer.png
  frontend/public/image/backlogTosprint.png
  frontend/public/image/clickStory.png
  frontend/public/image/completeSprint.png
  frontend/public/image/newStory.png
  frontend/public/image/startSprint.png
  frontend/public/image/story.png
  frontend/public/index.html
  frontend/src/components/Layout/index.jsx
  frontend/src/components/common/HelpComponent/index.jsx
  frontend/src/components/common/HelpSprintModal/index.jsx
  frontend/src/components/common/IntroduceHeader/index.jsx
  frontend/src/pages/BacklogAndSprint/index.jsx
Labels: Feat, FE
